

DROP TABLE IF EXISTS `User`;
      
CREATE TABLE `User` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `name` VARCHAR NOT NULL DEFAULT 'NULL',
  `login` VARCHAR NOT NULL DEFAULT 'NULL',
  `password` MEDIUMTEXT NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `Alarm`;
      
CREATE TABLE `Alarm` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `is_active` CHAR NOT NULL DEFAULT 'NULL',
  `id_User` INTEGER NULL DEFAULT NULL,
  `created_on` DATETIME NOT NULL DEFAULT 'NULL',
  `id_Medicine` INTEGER NULL DEFAULT NULL,
  `inits_on` DATETIME NOT NULL DEFAULT 'NULL',
  `type` INTEGER NOT NULL DEFAULT NULL,
  `id_AlarmNote` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `AlarmNote`;
      
CREATE TABLE `AlarmNote` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `note` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `StaticAlarm`;
      
CREATE TABLE `StaticAlarm` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `time` DATETIME NOT NULL DEFAULT 'NULL',
  `days` INTEGER NULL DEFAULT NULL,
  `id_Alarm` INTEGER NOT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `PeriodicAlarm`;
      
CREATE TABLE `PeriodicAlarm` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `alert_interval` TIMESTAMP NOT NULL DEFAULT 'NULL',
  `id_Alarm` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `Medicine`;
      
CREATE TABLE `Medicine` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `name` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`id`)
);

ALTER TABLE `Alarm` ADD FOREIGN KEY (id_User) REFERENCES `User` (`id`);
ALTER TABLE `Alarm` ADD FOREIGN KEY (id_Medicine) REFERENCES `Medicine` (`id`);
ALTER TABLE `Alarm` ADD FOREIGN KEY (id_AlarmNote) REFERENCES `AlarmNote` (`id`);
ALTER TABLE `StaticAlarm` ADD FOREIGN KEY (id_Alarm) REFERENCES `Alarm` (`id`);
ALTER TABLE `PeriodicAlarm` ADD FOREIGN KEY (id_Alarm) REFERENCES `Alarm` (`id`);
